### ISSUE TITLE
Should .postcolor have line-height set?

### ISSUE THREAD

**Issue by littlelark** [littlelark/jcink-the-breach#53]
```css
.postcolor {
    font-size: 12px;
    line-height: 160%;
}
```
It's making `heading-alitus` puffy. What else is it affecting?
